---
# tasks file for ansible-role-iked

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create iked.conf
  template:
    src: iked.conf.j2
    dest: "{{ iked_conf_file }}"
    mode: 0640
    validate: iked -n -f %s
  notify: Restart iked

- name: Start iked
  service:
    name: "{{ iked_service }}"
    state: started
